version: "3.5"

services:
  tasktool:
    image: tasktool:latest
    container_name: tasktool
    build:
      context: .
    volumes:
      - ./src:/tasktool/src/:z
      - tasktool-media:/tasktool/media
    ports:
      - 8080:8000
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: tasktool-postgres
    volumes:
      - psql-data:/var/lib/postgresql/data
    env_file:
      - .env

  adminer:
    image: adminer:latest
    container_name: tasktool-adminer
    ports:
      - 8082:8080
    env_file:
      - .env

volumes:
  psql-data:
  tasktool-media:
