# Generated by Django 5.0.1 on 2024-01-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
    ]
