# Generated by Django 5.0.1 on 2024-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
            ],
            options={
                'verbose_name': 'epic',
                'verbose_name_plural': 'epics',
                'ordering': ['title'],
            },
        ),
    ]
