# Generated by Django 5.0.1 on 2024-01-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='themes',
            field=models.ManyToManyField(to='agile.theme'),
        ),
    ]
