# Generated by Django 5.0.1 on 2024-01-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile', '0004_epic_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
